#!/usr/bin/with-contenv bash

cron_dir="/var/spool/cron/crontabs"
cron_file="$cron_dir/root"

rm -f "$cron_file"
touch "$cron_file"

if [[ "${RECREATE_VPN_CRON}" ]]; then
    echo "Create cron file"
    echo "$RECREATE_VPN_CRON /app/reconnect.sh" >> "$cron_file"
fi

exit 0
