#!/usr/bin/with-contenv bash

cron_dir="/var/spool/cron/crontabs"
cron_file="$cron_dir/root"

rm -f "$cron_file"
touch "$cron_file"

if [[ "${RECREATE_VPN_CRON}" ]]; then
    echo "Create con file"
    echo "$RECREATE_VPN_CRON sh -c '/etc/cont-init.d/50-createvpnconfig && s6-svc -h /var/run/s6/services/nordvpnd'" >> "$cron_file"
fi

exit 0
